
version: '3.8'

services:
  db:
    image: arm64v8/mysql:latest
    environment:
      - MYSQL_DATABASE=beach
      - MYSQL_ROOT_PASSWORD=Artfarts7
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Artfarts7
    ports:
      - "3300:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: ["mysqld"]

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/items?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    volumes: [./target/BB-0.0.1-SNAPSHOT.jar:/bb.jar]
    entrypoint: ["java", "-jar", "bb.jar"]
